LOCAL_FILE="$1"
BUCKET_NAME="$2"
EXPIRATION="$3"

FILE_NAME=$(basename "$LOCAL_FILE")
aws s3 cp "$LOCAL_FILE" "s3://$BUCKET_NAME/$FILE_NAME"
PRESIGNED_URL=$(aws s3 presign --expires-in "$EXPIRATION" "s3://$BUCKET_NAME/$FILE_NAME")
echo "$PRESIGNED_URL"
